/*
 * Simple Loan API
 * This is a loan API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.rabo.bank.loan.model;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * Lien
 */

@Embeddable
public class Lien {
	
	public Lien() {
		  
	  }
	public Lien(String name, Date creatTime, String resourceType, BigDecimal resourceValue) {
		super();
		this.name = name;
		this.creatTime = creatTime;
		this.resourceType = resourceType;
		this.resourceValue = resourceValue;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getCreatTime() {
		return creatTime;
	}

	public void setCreatTime(Date creatTime) {
		this.creatTime = creatTime;
	}

	public String getResourceType() {
		return resourceType;
	}

	public void setResourceType(String resourceType) {
		this.resourceType = resourceType;
	}

	public BigDecimal getResourceValue() {
		return resourceValue;
	}

	public void setResourceValue(BigDecimal resourceValue) {
		this.resourceValue = resourceValue;
	}

	private String name = null;

	private Date creatTime = null;

	private String resourceType = null;

	private BigDecimal resourceValue = null;


	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class Lien {\n");

		sb.append("    name: ").append(toIndentedString(name)).append("\n");
		sb.append("    creatTime: ").append(toIndentedString(creatTime)).append("\n");
		sb.append("    resourceType: ").append(toIndentedString(resourceType)).append("\n");
		sb.append("    resourceValue: ").append(toIndentedString(resourceValue)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}

