package com.rabo.bank.loan.model;
/*
 * Simple Loan API
 * This is a loan API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * LoanItem
 */
@Entity
public class Loan {
	public Loan() {

	}
	public Loan(Long loanNumber, BigDecimal loanAmount, BigDecimal loanManagementFees, String loanTerm,
			Date originationDate, String originationAccount, Lien lien, User borrower, String status) {
		super();
		this.loanNumber = loanNumber;
		this.loanAmount = loanAmount;
		this.loanManagementFees = loanManagementFees;
		this.loanTerm = loanTerm;
		this.originationDate = originationDate;
		this.originationAccount = originationAccount;
		this.lien = lien;
		this.borrower = borrower;
		this.status = status;
	}

	@Id
	private Long loanNumber = null;


	public Long getLoanNumber() {
		return loanNumber;
	}

	public void setLoanNumber(Long loanNumber) {
		this.loanNumber = loanNumber;
	}

	public BigDecimal getLoanAmount() {
		return loanAmount;
	}

	public void setLoanAmount(BigDecimal loanAmount) {
		this.loanAmount = loanAmount;
	}

	public BigDecimal getLoanManagementFees() {
		return loanManagementFees;
	}

	public void setLoanManagementFees(BigDecimal loanManagementFees) {
		this.loanManagementFees = loanManagementFees;
	}

	public String getLoanTerm() {
		return loanTerm;
	}

	public void setLoanTerm(String loanTerm) {
		this.loanTerm = loanTerm;
	}

	public Date getOriginationDate() {
		return originationDate;
	}

	public void setOriginationDate(Date originationDate) {
		this.originationDate = originationDate;
	}

	public String getOriginationAccount() {
		return originationAccount;
	}

	public void setOriginationAccount(String originationAccount) {
		this.originationAccount = originationAccount;
	}

	public Lien getLien() {
		return lien;
	}

	public void setLien(Lien lien) {
		this.lien = lien;
	}

	public User getBorrower() {
		return borrower;
	}

	public void setBorrower(User borrower) {
		this.borrower = borrower;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	private BigDecimal loanAmount = null;


	private BigDecimal loanManagementFees = null;


	private String loanTerm = null;


	private Date originationDate = null;


	private String originationAccount = null;

	@Embedded
	private Lien lien = null;
	
	@JsonIgnore
	private Integer userId = null;

	public Integer getUserId() {
		return userId;
	}
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Transient
	private User borrower = null;


	private String status = null;



	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class LoanItem {\n");

		sb.append("    loanNumber: ").append(toIndentedString(loanNumber)).append("\n");
		sb.append("    loanAmount: ").append(toIndentedString(loanAmount)).append("\n");
		sb.append("    loanManagementFees: ").append(toIndentedString(loanManagementFees)).append("\n");
		sb.append("    loanTerm: ").append(toIndentedString(loanTerm)).append("\n");
		sb.append("    originationDate: ").append(toIndentedString(originationDate)).append("\n");
		sb.append("    originationAccount: ").append(toIndentedString(originationAccount)).append("\n");
		sb.append("    lien: ").append(toIndentedString(lien)).append("\n");
		//sb.append("    borrower: ").append(toIndentedString(borrower)).append("\n");
		sb.append("    status: ").append(toIndentedString(status)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}

